export const ApiRoutes = {
	checkAuth: () => '/auth/check-auth',
	login: () => '/auth/login',
	logout: () => '/auth/logout',
	profile: () => '/api/profile',
	society: () => '/api/society',
	societyAvatar: () => '/api/avatar/society',
	search: () => '/api/search',
	societySearch: () => '/api/societies/search',
	societyJoin: (uuid: string) => `/api/society/${uuid}/join`,
	peer: (id?: string) => `/api/peer/${id}`,
	friends: () => '/api/friends',
	friendsCount: () => '/api/friends/counts',
	checkFriendship: () => '/api/friends/check',
	notification: () => '/api/notification',
	notificationCount: () => '/api/notification/count',
	avatar: () => '/api/avatar/user',
	optionOs: () => '/api/option/os',
	advert: () => '/api/advert',
	
	// Новые эндпоинты для регистрации
	checkEmail: () => '/auth/check_email',
	signup: () => '/auth/signup',
	confirmVerification: () => '/auth/confirm_verification',
}
