export const ApiRoutes = {
	// checkAuth: () => '/auth/check-auth',
	login: () => '/auth/v2/login',
	logout: () => '/auth/logout',
	profile: () => '/api/profile',
	society: () => '/api/society',
	societyAvatar: () => '/api/avatar/society',
	search: () => '/api/search',
	societySearch: () => '/api/societies/search',
	societyJoin: (uuid: string) => `/api/society/${uuid}/join`,
	peer: (id?: string) => `/api/peer/${id}`,
	friends: () => '/api/friends',
	friendsCount: () => '/api/friends/counts',
	checkFriendship: () => '/api/friends/check',
	notification: () => '/api/notification',
	notificationCount: () => '/api/notification/count',
	avatar: () => '/api/avatar/user',
	optionOs: () => '/api/option/os',
	advert: () => '/api/advert',

	// Новые эндпоинты для регистрации
	checkEmail: () => '/auth/check-email',
	sendCode: () => '/auth/send-code',
	registerUser: () => '/auth/register-user',
	confirmVerification: () => '/auth/confirm_verification',
	refreshToken: () => '/auth/refresh',
}
